#pragma once

#include "SpriteComponent.hpp"
#include "PositionComponent.hpp"
#include "TextureRectComponent.hpp"
#include "VelocityComponent.hpp"
#include "ControllableComponent.hpp"
#include "ParallaxComponent.hpp"
#include "MovableComponent.hpp"
#include "ScaleComponent.hpp"
#include "ButtonComponent.hpp"
#include "AnimationComponent.hpp"
#include "ScoreComponent.hpp"
#include "MusicComponent.hpp"
#include "TextComponent.hpp"
#include "RectangleShapeComponent.hpp"
#include "LoadingBarComponent.hpp"
#include "SoundComponent.hpp"
